"""fix_scrape_logs_schema

Revision ID: 0aa9fc164cf2
Revises: 480ab41767a7
Create Date: 2026-05-05 17:35:16.069728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa9fc164cf2'
down_revision: Union[str, Sequence[str], None] = '480ab41767a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_search'), table_name='jobs', postgresql_using='gin')
    op.create_index('ix_jobs_search', 'jobs', [sa.literal_column("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')
    op.add_column('scrape_logs', sa.Column('triggered_by', sa.String(length=100), nullable=True))
    op.add_column('scrape_logs', sa.Column('jobs_duplicates', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_logs', 'jobs_duplicates')
    op.drop_column('scrape_logs', 'triggered_by')
    op.drop_index('ix_jobs_search', table_name='jobs', postgresql_using='gin')
    op.create_index(op.f('ix_jobs_search'), 'jobs', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
