"""Add users table

Revision ID: 480ab41767a7
Revises: 6ac4dabb6115
Create Date: 2026-04-10 09:03:11.057322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480ab41767a7'
down_revision: Union[str, Sequence[str], None] = '6ac4dabb6115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_search'), table_name='jobs', postgresql_using='gin')
    op.create_index('ix_jobs_search', 'jobs', [sa.literal_column("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_search', table_name='jobs', postgresql_using='gin')
    op.create_index(op.f('ix_jobs_search'), 'jobs', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
