"""add unique constraint tocompany name

Revision ID: 6ac4dabb6115
Revises: 83ea8e577315
Create Date: 2026-03-20 01:37:13.334237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac4dabb6115'
down_revision: Union[str, Sequence[str], None] = '83ea8e577315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_companies_name'), 'companies', ['name'])
    op.drop_index(op.f('ix_jobs_search'), table_name='jobs', postgresql_using='gin')
    op.create_index('ix_jobs_search', 'jobs', [sa.literal_column("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_search', table_name='jobs', postgresql_using='gin')
    op.create_index(op.f('ix_jobs_search'), 'jobs', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('uq_companies_name'), 'companies', type_='unique')
    # ### end Alembic commands ###
