"""add_error_traceback_to_scrape_logs_schema

Revision ID: 790a7319e45b
Revises: ae906292dab6
Create Date: 2026-05-05 18:38:07.282800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790a7319e45b'
down_revision: Union[str, Sequence[str], None] = 'ae906292dab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_search'), table_name='jobs', postgresql_using='gin')
    op.create_index('ix_jobs_search', 'jobs', [sa.literal_column("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')
    op.add_column('scrape_logs', sa.Column('error_traceback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_logs', 'error_traceback')
    op.drop_index('ix_jobs_search', table_name='jobs', postgresql_using='gin')
    op.create_index(op.f('ix_jobs_search'), 'jobs', [sa.literal_column("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
