"""Initial tables

Revision ID: 83ea8e577315
Revises: 
Create Date: 2026-03-20 00:37:14.339401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83ea8e577315'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('companies',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('logo_url', sa.String(length=225), nullable=True),
    sa.Column('industry', sa.String(length=225), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('employees_label', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_table('scrape_logs',
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('site_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('search_term', sa.String(length=255), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_logs')),
    sa.UniqueConstraint('task_id', name=op.f('uq_scrape_logs_task_id'))
    )
    op.create_table('job_category_keywords',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_job_category_keywords_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_category_keywords'))
    )
    op.create_table('jobs',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_url', sa.String(length=2048), nullable=False),
    sa.Column('job_url_hash', sa.String(length=64), nullable=False),
    sa.Column('source_site', sa.String(length=50), nullable=False),
    sa.Column('location_city', sa.String(length=255), nullable=True),
    sa.Column('location_state', sa.String(length=255), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('salary_interval', sa.String(length=20), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('date_scraped', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_jobs_category_id_categories')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_jobs_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_job_url_hash'), 'jobs', ['job_url_hash'], unique=True)
    op.create_index('ix_jobs_location', 'jobs', ['location_country', 'location_state', 'location_city'], unique=False)
    op.create_index('ix_jobs_search', 'jobs', [sa.literal_column("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_search', table_name='jobs', postgresql_using='gin')
    op.drop_index('ix_jobs_location', table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_url_hash'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('job_category_keywords')
    op.drop_table('scrape_logs')
    op.drop_table('companies')
    op.drop_table('categories')
    # ### end Alembic commands ###
