"""add_status_timestamp_indeces_to_scrape_logs_schema

Revision ID: ae906292dab6
Revises: 0aa9fc164cf2
Create Date: 2026-05-05 17:44:17.537925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae906292dab6'
down_revision: Union[str, Sequence[str], None] = '0aa9fc164cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_search'), table_name='jobs', postgresql_using='gin')
    op.create_index('ix_jobs_search', 'jobs', [sa.literal_column("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')
    op.create_index('ix_scrape_logs_started_at', 'scrape_logs', ['started_at'], unique=False)
    op.create_index('ix_scrape_logs_status', 'scrape_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scrape_logs_status', table_name='scrape_logs')
    op.drop_index('ix_scrape_logs_started_at', table_name='scrape_logs')
    op.drop_index('ix_jobs_search', table_name='jobs', postgresql_using='gin')
    op.create_index(op.f('ix_jobs_search'), 'jobs', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
