"""trim_scrape_logs_columns

Revision ID: b4d1a2c3e9f0
Revises: 790a7319e45b
Create Date: 2026-05-07 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4d1a2c3e9f0"
down_revision: Union[str, Sequence[str], None] = "790a7319e45b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scrape_logs", "search_term")
    op.drop_column("scrape_logs", "jobs_updated")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scrape_logs",
        sa.Column("jobs_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.alter_column("scrape_logs", "jobs_updated", server_default=None)
    op.add_column("scrape_logs", sa.Column("search_term", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
