categories:
  backend:
    - backend engineer
    - python developer
    - java developer

  frontend:
    - frontend engineer
    - react engineer
    - javascript

  data:
    - data engineer
    - data analyst
    - machine learning engineer
    - ai engineer

  devops:
    - devops engineer
    - site reliability engineer
